fix entrypoint.sh to detect the --config and --plugin options
fluent/fluentd-docker-image pull request #282
Opened 2021-06-29 09:30 UTC by edentsai

If we custom the config and plugin in long options (--config and --plugin),
entrypoint.sh still append the -c and -p options with default value to the
fluentd command.

for example, I ran a fluentd container below:

```bash
docker container run fluent/fluentd:v1.12-1 fluentd \
    --config /fluentd/etc/my-fluent.conf \
    --plugin /fluentd/my-plugins
```

the entrypoint.sh will append the default options to the command:

```bash
fluentd \
    --config /fluentd/etc/my-fluent.conf \
    --plugin /fluentd/my-plugins \
    -c /fluentd/etc/fluent.conf \
    -p /fluentd/plugins
```

I also confirmed the --config and --plugin options are supported
since Fluentd v0.9.0 and v1.0, the changes should be compatible safety.

- https://github.com/fluent/fluentd/blob/v0.9.0/lib/fluent/command/fluentd.rb#L32-L38
- https://github.com/fluent/fluentd/blob/v1.0.0/lib/fluent/command/fluentd.rb#L35-L41

References:

- https://docs.fluentd.org/deployment/command-line-option#fluentd

2021-06-29 09:38 UTC, edentsai commented
Could somebody help me to verify that does the `grep -e '...'` command works in the docker image on Windows platform
because I don't have a PC with MS Windows operating system to verify it

- v1.10/windows/entrypoint.sh
- v1.12/windows-2004/entrypoint.sh
- v1.12/windows-20H2/entrypoint.sh
- ...etc

thanks.

2021-07-01 08:11 UTC, kenhys commented
At least, it seems that entrypoint.sh is not used for windows images.

2021-07-05 02:24 UTC, cosmo0920 commented
Windows image uses `cmd` instead of shell script to create ENTRYPOINT:
https://github.com/fluent/fluentd-docker-image/blob/master/v1.13/windows-20H2/Dockerfile#L39

2021-07-05 02:26 UTC, cosmo0920 requested changes
These changes sound reasonable for me.
But, v0.12, 0.14, and between 1.0 and 1.11 are not maintained for now.
Could you change only for 1.12 and 1.13 images?

2021-07-05 07:04 UTC, edentsai commented
OK, I will update it later.

2021-07-07 11:33 UTC, edentsai commented
PR updated.

2021-07-13 04:32 UTC, kenhys approved these changes
LGTM.

2021-07-18 12:43 UTC, cosmo0920 approved these changes

2021-07-19 01:11 UTC, merged

2021-07-19 01:11 UTC, kenhys commented
thanks, @edentsai